id: P001661
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:13:09.217148
source_metadata:
  id: bdr:W27414
  title: དམ་ཅན་བསྟན་སྲུང་རྒྱ་མཚོའི་རྣམ་ཐར།（ཕ་ཇོ་ལྡིང་འོག་མིན་གཉིས་པར་བཞུགས་པའི་དབུ་ཅན་བྲིས་མ།）
  author: ''
  volumes:
    d86eff587e6e42f0be2d430999a106ec:
      image_group_id: I4335
      title: ''
      volume_number: 1
      total_pages: 674
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
