id: opecha:P001661
initial_creation_type: ocr
source_metadata:
  id: bdr:W27414
  title: དམ་ཅན་བསྟན་སྲུང་རྒྱ་མཚོའི་རྣམ་ཐར།（ཕ་ཇོ་ལྡིང་འོག་མིན་གཉིས་པར་བཞུགས་པའི་དབུ་ཅན་བྲིས་མ།）
  volume: ''
  author: ''
