id: I52A0B6D2
legacy_id: P001661
ocr_import_info:
  bdrc_scan_id: W27414
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:18:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:15:40.213061+00:00'
last_modified: 2022-09-02 15:16:27.387047
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27414
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW27414
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཅན་བསྟན་སྲུང་རྒྱ་མཚོའི་རྣམ་ཐར།（ཕ་ཇོ་ལྡིང་འོག་མིན་གཉིས་པར་བཞུགས་པའི་དབུ་ཅན་བྲིས་མ།）
  author: འོལ་དགའ་རྗེ་དྲུང ༠༣་བཞད་པའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6198533428929373
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I4335:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4335
      total_pages: 674
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4335.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6198533428929373
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
