id: I52A0B6D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:23:06+00:00'
last_modified: '2022-06-07T13:56:33.646959+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27414
  title: དམ་ཅན་བསྟན་སྲུང་རྒྱ་མཚོའི་རྣམ་ཐར།（ཕ་ཇོ་ལྡིང་འོག་མིན་གཉིས་པར་བཞུགས་པའི་དབུ་ཅན་བྲིས་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D180:
      image_group_id: I4335
      title: ''
      total_pages: 674
      order: 1
      base_file: D180.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
